modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Dave's License"

[[mods]] #mandatory
modId="metalbushesmod" #mandatory
version="1.17.1-2.7" #mandatory
displayName="Metal Bushes" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks to early Tinkers Consturct!" #optional
authors="Dave" #optional
description='''
Remember early Tinkers Contruct with the fancy little Metal Bushes?

Now it comes alive with the new Bushes in Minecraft. Have Fun!
'''


[[dependencies.metalbushesmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"


[[dependencies.metalbushesmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"
