modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Timebreaker900/MetalBushesMod/issues"

[[mods]]
modId="metalbushesmod"
version="1.4.4"
displayName="Metal Bushes Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/metal-bushes"
credits="Thanks to early Tinkers Consturct!"
authors="Dave"
description='''
Remeber early Tinkers Contruct with the fancy little Metal Bushes?

Now it comes alive with the new Bushes in Minecraft. Have Fun!
'''

[[dependencies.metalbushesmod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.metalbushesmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"